# Generated by Django 4.2.6 on 2023-11-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INST', '0004_commentary_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
