# Generated by Django 4.2.6 on 2024-01-28 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INST', '0006_user_my_web_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('day_mod', models.DateTimeField(auto_now=True)),
                ('save', models.ManyToManyField(related_name='save', to='INST.postt')),
                ('user_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
