# Generated by Django 4.2.6 on 2024-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INST', '0008_rename_save_saveposts_saves_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='int_sub',
            field=models.IntegerField(default=0),
        ),
    ]
